# Generated by Django 2.1.1 on 2018-09-24 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.PositiveSmallIntegerField()),
                ('speed', models.PositiveSmallIntegerField()),
                ('direction', models.BooleanField()),
                ('soundOptions', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
