# Generated by Django 2.1.1 on 2018-09-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='hornIs',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='train',
            name='lightsOn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='train',
            name='silentRunning',
            field=models.BooleanField(default=False),
        ),
    ]
