# Generated by Django 2.1.1 on 2018-09-27 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_auto_20180924_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.PositiveSmallIntegerField()),
                ('type', models.CharField(max_length=200)),
                ('brightness', models.PositiveSmallIntegerField()),
                ('colour', models.PositiveSmallIntegerField()),
                ('lightsState', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
