# Generated by Django 2.1.1 on 2018-09-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0003_light'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='hexValue',
            field=models.CharField(default='#_000000', max_length=200),
            preserve_default=False,
        ),
    ]
